FROM balenalib/%%BALENA_MACHINE_NAME%%-golang:latest-build AS build

WORKDIR /go/src/github.com/ryanyogan/gobot-blink/app

COPY /app ./

RUN go get -d -v ./...
RUN go install -v ./...
RUN go build

FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:stretch

COPY --from=build /go/src/github.com/ryanyogan/gobot-blink/app/ .

CMD ["./app"]
